export const DB_NAME = "quickmelody";

export const USER_TABLE =
  "CREATE TABLE IF NOT EXISTS users (id INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(255), password VARCHAR(255), email VARCHAR(255), created_at DATETIME DEFAULT CURRENT_TIMESTAMP)";

export const SONG_TABLE =
  "CREATE TABLE IF NOT EXISTS songs (id INT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(255), artist VARCHAR(255), album VARCHAR(255), genre VARCHAR(255), duration INT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)";

export const PLAYLIST_TABLE =
  "CREATE TABLE IF NOT EXISTS playlists (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255), user_id INT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id))";

export const PLAYLIST_SONG_TABLE =
  "CREATE TABLE IF NOT EXISTS playlist_songs (id INT PRIMARY KEY AUTO_INCREMENT, playlist_id INT, song_id INT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(playlist_id) REFERENCES playlists(id), FOREIGN KEY(song_id) REFERENCES songs(id))";

export const ALBUM_TABLE =
  "CREATE TABLE IF NOT EXISTS albums (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255), song_id INT, artist VARCHAR(255), genre VARCHAR(255), release_date DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(song_id) REFERENCES songs(id))";
