export const DB_NAME = "quickmelody";

export const USER_TABLE = `CREATE TABLE IF NOT EXISTS users (id INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, image VARCHAR(255) DEFAULT "https://media.istockphoto.com/id/1403254696/vector/cheerful-man-with-headphones.jpg?s=612x612&w=0&k=20&c=OKUZW-rLxVz1c-WWKf0biB4NHF7l_S6aSBGjWmmv8NU=",created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`;

export const ARTIST_TABLE = `
  CREATE TABLE IF NOT EXISTS artists (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    bio TEXT,
    image VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )
`;

export const ALBUM_TABLE = `CREATE TABLE IF NOT EXISTS albums (id INT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(255) NOT NULL, artist_id INT NOT NULL, image VARCHAR(255), genre VARCHAR(255), release_date DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE)`;

export const SONG_TABLE = `CREATE TABLE IF NOT EXISTS songs (id INT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(255) NOT NULL, artist_id INT NOT NULL, album_id INT, genre VARCHAR(255), duration INT NOT NULL, total_likes INT DEFAULT 0, image VARCHAR(255), created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE, FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE SET NULL)`;

export const PLAYLIST_TABLE = `CREATE TABLE IF NOT EXISTS playlists (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL, user_id INT NOT NULL,  description VARCHAR(255), image VARCHAR(255), created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`;

export const PLAYLIST_SONG_TABLE =
  "CREATE TABLE IF NOT EXISTS playlist_songs (id INT PRIMARY KEY AUTO_INCREMENT, playlist_id INT NOT NULL, song_id INT NOT NULL, position INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(playlist_id) REFERENCES playlists(id) ON DELETE CASCADE, FOREIGN KEY(song_id) REFERENCES songs(id) ON DELETE CASCADE)";

export const LIKES_TABLE = `
  CREATE TABLE IF NOT EXISTS likes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    song_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE
  )
`;
